# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Configure git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Get release version
        run: |
          echo "app_version=${{ node get-version.js }}" >> $GITHUB_ENV
          echo "${{ env.app_version }}"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run release --if-present
      - name: Commit changes
        run: |
          git add dist/*
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Release version ${{ env.app_version }}" -a
            git tag ${{ env.app_version }}
          fi
      - name: Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
